### ISSUE TITLE
Please, make a documentation for terminal commands. Or is it deno terminal?

### ISSUE THREAD

**Issue by orzklv** [fakoua/deno_gui#1]

**Comment by fakoua** [comment]
Hi, 
The terminal is still under construction, sorry for the lake of docs, will update asap.

**Comment by orzklv** [comment]
> Hi,
> The terminal is still under construction, sorry for the lake of docs, will update asap.

Thanks for your attention bro) 😉

**Comment by fakoua** [comment]
@genemators Please check v2.0:

deno run -A -r --unstable https://deno.land/x/deno_gui/gui.ts

Terminal is now REPL

**Comment by orzklv** [comment]
Wow, works great and stable. Now this is one of the deno's must have tools =)

**Comment by fakoua** [comment]
Many thanks @genemators , please check the latest version I added and new cool feature (Examples) in the Web REPL.
