### ISSUE TITLE
It isn't running on `deno` version `1.11.1`

### ISSUE THREAD

**Issue by nahinakbar** [fakoua/deno_gui#6]
**Describe the bug**
I get the following error while running `deno run -A --unstable  https://deno.land/x/deno_gui/mod.ts`

`error: EOF while parsing a value at line 1 column 0
    at https://deno.land/std@0.102.0/flags/mod.ts:3:0`

**To Reproduce**
1. Open a terminal
2. run `deno run -A --unstable  https://deno.land/x/deno_gui/mod.ts`
3. See error

**Expected behavior**
I expect it to run as shown in the README file

**Screenshots**
![image](https://user-images.githubusercontent.com/27775584/126775651-758e9da5-4fb0-4c1a-b706-9184ce321f32.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Version 1.11.1

**Comment by nahinakbar** [comment]
I got it working by using `-r` agument on the command line

**Comment by fakoua** [comment]
Hi @nahinakbar, 
Thanks for your feedback, yes it is related to older libs.

Sameh
